# Defines an environment
nodes:

# Node with single deployment
- node: localhost
  roles:
  - role: tomcat
  - role: sample-app


# Global configuration
config:

  jvm.path: C:\Java\jdk1.8.0_152
  tomcat.path: C:\apache-tomcat-8.5.23

  sampleApp:
    welcomeMessage: Hello World, welcome single app!
