# Defines an environment
nodes:

# Node with single deployment
- node: localhost
  roles:
  - role: tomcat
  - role: sample-app


# Global configuration
config:

  jvm.path: "C:\\Program Files\\Java\\jdk1.8.0_201"
  tomcat.path: C:\Java\apache-tomcat-9.0.30

  sampleApp:
    welcomeMessage: Hello World, welcome single app!
