# Defines an environment
nodes:

# Node 1
- node: prod1
  roles:
  - role: tomcat
  - role: sample-app
  config: 
    jvm:
      heapspace:
        max: 1024m
  
# Node 2
- node: prod2
  roles:
  - role: tomcat
  - role: sample-app
  config: 
    jvm:
      heapspace:
        max: 2048m

# Global configuration
config:

  jvm.path: "C:\\Program Files\\Java\\jdk1.8.0_201"
  tomcat.path: C:\Java\apache-tomcat-9.0.30

  sampleApp:
    welcomeMessage: Hello World, welcome on the prod environment

